# Generated by Django 2.2.3 on 2019-12-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(auto_created=True, verbose_name='注册时间')),
                ('user_name', models.CharField(max_length=45, verbose_name='用户名')),
                ('user_pwd', models.CharField(max_length=45, verbose_name='密码')),
                ('user_mobile', models.CharField(max_length=45, verbose_name='手机号')),
                ('user_icon', models.CharField(max_length=45, verbose_name='头像')),
                ('user_real_name', models.CharField(max_length=45, verbose_name='真实姓名')),
                ('user_identity_card', models.CharField(max_length=45, verbose_name='身份证')),
                ('user_nick_name', models.CharField(max_length=45, verbose_name='昵称')),
                ('user_gender', models.CharField(max_length=45, verbose_name='性别')),
                ('user_birthday', models.CharField(max_length=45, verbose_name='生日')),
                ('user_address', models.CharField(max_length=45, verbose_name='居住地')),
                ('user_sign', models.CharField(max_length=45, verbose_name='个性签名')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
