# Generated by Django 2.2.4 on 2019-12-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_cardgoods_category_goodsinfo_goodssku_messageinfo_ordergoods_orderinfo_shipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipaddress',
            name='userTable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.UserTable', verbose_name='用户信息'),
        ),
    ]
