# Generated by Django 2.2.4 on 2019-12-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20191230_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageinfo',
            name='user_id',
        ),
    ]
