# Generated by Django 2.2.4 on 2019-12-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_remove_messageinfo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='shipaddress',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='ship_id',
            field=models.SmallIntegerField(max_length=11, verbose_name='发货id'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_price',
            field=models.BigIntegerField(verbose_name='总价'),
        ),
    ]
