# Generated by Django 2.2.4 on 2019-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20191230_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageinfo',
            name='userTable',
        ),
        migrations.AddField(
            model_name='messageinfo',
            name='userTable',
            field=models.ManyToManyField(to='shopping.UserTable', verbose_name='用户信息'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='ship_id',
            field=models.SmallIntegerField(verbose_name='发货id'),
        ),
    ]
