# Generated by Django 2.2.4 on 2019-12-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20191230_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '商品分类表', 'verbose_name_plural': '商品分类表'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='分类描述'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Category', verbose_name='商品分类'),
        ),
    ]
