# Generated by Django 2.2.4 on 2019-12-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20191230_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsinfo',
            name='goods_banner',
        ),
        migrations.CreateModel(
            name='GoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='轮播图')),
                ('goodsInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.GoodsInfo', verbose_name='商品信息表')),
            ],
            options={
                'verbose_name': '商品信息轮播图表',
                'verbose_name_plural': '商品信息轮播图表',
            },
        ),
    ]
