# Generated by Django 2.2.4 on 2019-12-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_auto_20191230_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsbanner',
            name='goodsInfo',
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='banner',
            field=models.ManyToManyField(to='shopping.GoodsBanner', verbose_name='轮播图'),
        ),
    ]
