# Generated by Django 2.2.4 on 2019-12-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_auto_20191230_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssku',
            name='goods_id',
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='sku',
            field=models.ManyToManyField(to='shopping.GoodsSku', verbose_name='商品属性'),
        ),
    ]
