# Generated by Django 2.2.4 on 2020-01-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20191231_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/category/', verbose_name='分类图片'),
        ),
        migrations.AlterField(
            model_name='goodsbanner',
            name='url',
            field=models.ImageField(upload_to='image/goods/', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_default_icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/goods/', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='messageinfo',
            name='msg_icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/message/', verbose_name='消息图片'),
        ),
        migrations.AlterField(
            model_name='shipaddress',
            name='ship_is_default',
            field=models.SmallIntegerField(choices=[(0, '默认'), (1, '非默认')], default=1, verbose_name='是否默认'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/user/', verbose_name='头像'),
        ),
    ]
